default: &default
  user: postgres
  password: 23490bd5
  encoding: UTF-8
  pool: 5
  adapter: postgresql
  timeout: 5000
 
development:
  <<: *default
  database: rubyProject_development
 
production:
  <<: *default
  database: rubyProject_production
 
test:
  <<: *default
  database: rubyProject_test